name: test making binaries

on:
  push:
    tags:
    - 'v__*'

jobs:
  build:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    environment: TEST_PYPI_API_TOKEN
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.9']
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
          python-version: ${{ matrix.python-version }}
    
    - name: Upgrade pip
      run: |
            pip install --upgrade pip
            pip install --upgrade build
    
    - name: Install cibuildwheel
      run: python -m pip install cibuildwheel

    - name: Build wheels (ubuntu-latest)        
      if: matrix.os == 'ubuntu-latest'
      run: python -m cibuildwheel --output-dir dist

    - name: Build wheels (macos-latest)
      if: matrix.os == 'macos-latest'
      run: |
        python --version
        brew install llvm
        export LIBRARY_PATH="/usr/local/opt/llvm/lib"
        python -m cibuildwheel --output-dir dist

    - name: Build wheels (windows-latest)      
      if: matrix.os == 'windows-latest'
      run: python -m cibuildwheel --output-dir dist
      
    - name: Install twine
      run: python -m pip install twine

    - name: Upload to TestPyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        TWINE_REPOSITORY: testpypi
        skip_existing: true
      run: python -m twine upload --skip-existing --verbose dist/*        
      
    - uses: actions/upload-artifact@v2
      with:
        path: ./dist/*.whl
